- include_tasks: "centos.yml"
  when: ansible_os_family == 'RedHat'

- include_tasks: "ubuntu.yml"
  when: ansible_os_family == 'Debian'

# - name: "DEBUG - host specific vars for dcore container"
#   debug:
#     var: dcore_container

- name: "Define list of seeders and witnesses"
  set_fact:
    list_of_seeders:   "{{ dcore_containers | dict2items | selectattr('value.role', 'equalto', 'seeder') | map(attribute='key') | list }}"
    list_of_witnesses: "{{ dcore_containers | dict2items | selectattr('value.role', 'equalto', 'witness') | map(attribute='key') | list }}"

# - name: "DEBUG - List of seeders"
#   debug:
#     msg: "{{ list_of_seeders }}"
#
# - name: "DEBUG - List of witnesses"
#   debug:
#     msg: "{{ list_of_witnesses }}"

- name: "Include dcore_instance.yml task for dcore container with witness role"
  include_tasks: dcore_instance.yml
  vars:
    processed_container: "{{ item }}"
  loop: "{{ list_of_witnesses }}"

- name: "Include dcore_instance.yml task for dcore container with seeder role"
  include_tasks: dcore_instance.yml
  vars:
    processed_container: "{{ item }}"
  loop: "{{ list_of_seeders }}"
