- include_tasks: "centos.yml"
  when: ansible_os_family == 'RedHat'

- include_tasks: "ubuntu.yml"
  when: ansible_os_family == 'Debian'

# - name: "DEBUG - host specific vars for dcore container"
#   debug:
#     var: dcore_container

- name: "Define list of dcore instances"
  set_fact:
    list_of_dcors:     "{{ dcore_containers | dict2items | map(attribute='key') | list }}"

# - name: "DEBUG - List of dcore instances"
#   debug:
#     msg: "{{ list_of_dcors }}"

- name: "Include dcore_instance.yml task for all dcore container"
  include_tasks: dcore_instance.yml
  vars:
    processed_container: "{{ item }}"
  loop: "{{ list_of_dcors }}"
